### ISSUE TITLE
change color of links

### ISSUE THREAD

**Issue by ozanj** [ozanj/rclass#2]
change color of links to a blue that stands out from regular black text
@cyouh95 @mpatricia01

**Comment by mpatricia01** [comment]
Hi Ozan,

Not sure if you want to change all links to blue, but this is what I did for the "Things to do" document. 
![screen shot 2018-09-26 at 12 25 46 pm](https://user-images.githubusercontent.com/33170829/46104202-9cc98b80-c187-11e8-87ce-954af8e5164b.png)

**Comment by mpatricia01** [comment]
This is how it looks.  

![screen shot 2018-09-26 at 12 32 11 pm](https://user-images.githubusercontent.com/33170829/46104472-43ae2780-c188-11e8-9945-0970a7d09402.png)
![screen shot 2018-09-26 at 12 32 17 pm](https://user-images.githubusercontent.com/33170829/46104473-43ae2780-c188-11e8-9fa4-2f91e184f30e.png)

**Comment by ozanj** [comment]
Thank you!
