### ISSUE TITLE
investigate whether possible to add grey background to `inline code`

### ISSUE THREAD

**Issue by ozanj** [ozanj/rclass#3]
When typing text in .Rmd file [not in a code chunk] the text enclosed in single back ticks `` is formatted as code.

When creating an html_document in RMarkdown, inline `code` is given a grey background [and typewriter font] once the document is knit.

however, when creating a beamer_presentation (or pdf document), inline `code` is not given a grey background. instead it is just given typewriter font.

to get over this problem, I created a simple latex command \hlgc{} to give grey background. for several reasons, I don't won't to use this function anymore. rather, I just want to use backticks ``. My question is whether it is possible to write/modify some function such that code in back ticks is given typewriter font AND grey background? 
@cyouh95 @mpatricia01

**Comment by mpatricia01** [comment]
Hi Ozan,

I've been trying to figure this out for hours and no luck. It also took me a while because I was receiving errors when I tried to knit to pdf when using latex code in file.

**Comment by cyouh95** [comment]
Perhaps we could redefine the `\texttt` command:
```latex
\let\OldTexttt\texttt
\renewcommand{\texttt}[1]{\OldTexttt{\hlg{#1}}}
```
