### ISSUE TITLE
vertical space in bullets

### ISSUE THREAD

**Issue by ozanj** [ozanj/rclass#4]
slightly increase space between bullets of the same "level", for all bullet levels up to 3. [Patricia - you were the one that mentioned this to me]

slightly decrease space between bullets of a different level. For example, notice that there is more space between a level-1 bullet and a level-2 bullet. the vertical space between a level-1 bullet and a level-2 bullet should be the same as vertical space between two level-1 bullets.

@cyouh95 @mpatricia01

**Comment by cyouh95** [comment]
The exact numbers here could be adjusted, but I think we can use this for increasing space between bullets of the same level:
```latex
\let\olditem\item
\renewcommand{\item}{%
  \olditem\vspace{4pt}
}
```

and this for decreasing space between bullets of different levels:
```latex
% decreasing space before and after level-2 bullet block
\addtobeamertemplate{itemize/enumerate subbody begin}{}{\vspace*{-3pt}}
\addtobeamertemplate{itemize/enumerate subbody end}{}{\vspace*{-3pt}}

% decreasing space before and after level-3 bullet block
\addtobeamertemplate{itemize/enumerate subsubbody begin}{}{\vspace*{-2pt}}
\addtobeamertemplate{itemize/enumerate subsubbody end}{}{\vspace*{-2pt}}
```

![screen shot 2018-09-26 at 5 04 28 pm](https://user-images.githubusercontent.com/25449416/46116085-22146680-c1af-11e8-8b89-eb0588a462fa.png)
